### ISSUE TITLE
Composer でインストール

### ISSUE THREAD

**Issue by ttsuru** [webpay/mdl_webpay#9]
Composer プラグイン経由で EC-CUBE のモジュールをインストールできるプラグインを作りました。
https://github.com/ec-cube-plugin/plugin-installer/tree/2.13

LGPLでしたので、以下の2つに Fork して対応してみました。
https://github.com/ttsuru/mdl_webpay
https://github.com/ttsuru/WebPayExt

Packagistにサンプルで以下の2つとして登録しました。
https://packagist.org/packages/ttsuru/mdl_webpay
https://packagist.org/packages/ttsuru/web_pay_ext

EC-CUBEのルートにある `composer.json` を以下のようにするだけで `mdl_webpay` がインストールできるようになっています。
```
{
    "require": {
        "ttsuru/mdl_webpay": "*",
        "ttsuru/web_pay_ext": "*"
    }
}
```

```sh
$ composer install --no-dev
```

PackagistにWebpayさんの方で登録いただけるようでしたら、上記の2つは削除しておきます。
また、プルリクもさせていただきますが、いかがでしょうか。

**Comment by ttsuru** [comment]
:cry:

**Comment by hmsk** [comment]
ご回答永らくお待たせ致しました。
https://github.com/ec-cube-plugin/plugin-installer のような取り組み、素晴らしいですね。ご提案ありがとうございます。

誠に申し訳ないのですが、WebPayとしては現状EC-CUBE向けのプラグインについて継続的な開発という意味合い（直近でいうと3.0への対応など）を含めてPackagistへの掲載を決断出来ない状況でございます。現状 @ttsuru さんの御判断で独自に公開を行なわれているという認識とさせてください。

**Comment by ttsuru** [comment]
@hmsk 
本件、ご連絡ありがとうございます。
EC-CUBEの非公式モジュールや開発段階ではインストールが非常に煩雑になりますので、
Composerを利用した開発が非常にメリットがあると感じています。

また、Packagistについても問題があるようでしたらすぐに削除いたしますので、ご連絡ください。

https://github.com/ec-cube-plugin/plugin-installer については3系への対応も検討しております。
